packages:
  - packages/*
  - packages/nuxt/playground

catalog:
  "@nuxt/kit": ^4.4.2
  "@nuxt/devtools": ^3.2.4
  "@nuxt/eslint-config": ^1.15.2
  "@nuxt/schema": ^4.4.2
  "@nuxt/test-utils": ^4.0.0
  "@types/node": latest
  "@vue/compiler-sfc": ^3.5.31
  changelogen: ^0.6.2
  eslint: ^10.1.0
  h3: 2.0.1-rc.20
  nuxt: ^4.4.2
  oxc-parser: ^0.121.0
  pathe: ^2.0.3
  tinyglobby: ^0.2.15
  tsdown: latest
  typescript: ~6.0.2
  ufo: ^1.6.3
  vitest: ^4.1.2
  vue-tsc: ^3.2.6
  vite: ^8.0.3
  vue: ^3.5.30
  jiti: ^2.6.1
  nitro: 3.0.260311-beta
  ofetch: ^1.5.1

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  unrs-resolver: true

overrides:
  vite: ^8.0.3
